DROP TABLE IF EXISTS archives;
DROP TABLE IF EXISTS drafts;
DROP TABLE IF EXISTS oracle;

CREATE TABLE oracle (
  card VARCHAR(200) PRIMARY KEY,
  releaseDate DATE NOT NULL
);

ALTER TABLE oracle
  ADD FULLTEXT(card) WITH PARSER ngram;
